//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDocsDN_File_Server_Operations.FileServer {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="File_Data", Namespace="http://schemas.datacontract.org/2004/07/eDocsDN_Get_Directory_Info")]
    [System.SerializableAttribute()]
    public partial class File_Data : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Convert_To_PDFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] DataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Destination_DirectoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Destination_File_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DirectoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Draft_VersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string File_NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eDocsDN_File_Server_Operations.FileServer.File_Operations File_OperationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool PrintFormDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Remove_Scan_SignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Serial_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Source_DirectoryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Source_File_CheckSumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SurrKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool TrackChangesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string User_IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckSum {
            get {
                return this.CheckSumField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckSumField, value) != true)) {
                    this.CheckSumField = value;
                    this.RaisePropertyChanged("CheckSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Convert_To_PDF {
            get {
                return this.Convert_To_PDFField;
            }
            set {
                if ((this.Convert_To_PDFField.Equals(value) != true)) {
                    this.Convert_To_PDFField = value;
                    this.RaisePropertyChanged("Convert_To_PDF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destination_Directory {
            get {
                return this.Destination_DirectoryField;
            }
            set {
                if ((object.ReferenceEquals(this.Destination_DirectoryField, value) != true)) {
                    this.Destination_DirectoryField = value;
                    this.RaisePropertyChanged("Destination_Directory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Destination_File_Name {
            get {
                return this.Destination_File_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.Destination_File_NameField, value) != true)) {
                    this.Destination_File_NameField = value;
                    this.RaisePropertyChanged("Destination_File_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Directory {
            get {
                return this.DirectoryField;
            }
            set {
                if ((object.ReferenceEquals(this.DirectoryField, value) != true)) {
                    this.DirectoryField = value;
                    this.RaisePropertyChanged("Directory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Draft_Version {
            get {
                return this.Draft_VersionField;
            }
            set {
                if ((this.Draft_VersionField.Equals(value) != true)) {
                    this.Draft_VersionField = value;
                    this.RaisePropertyChanged("Draft_Version");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string File_Name {
            get {
                return this.File_NameField;
            }
            set {
                if ((object.ReferenceEquals(this.File_NameField, value) != true)) {
                    this.File_NameField = value;
                    this.RaisePropertyChanged("File_Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eDocsDN_File_Server_Operations.FileServer.File_Operations File_Operations {
            get {
                return this.File_OperationsField;
            }
            set {
                if ((object.ReferenceEquals(this.File_OperationsField, value) != true)) {
                    this.File_OperationsField = value;
                    this.RaisePropertyChanged("File_Operations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PrintFormData {
            get {
                return this.PrintFormDataField;
            }
            set {
                if ((this.PrintFormDataField.Equals(value) != true)) {
                    this.PrintFormDataField = value;
                    this.RaisePropertyChanged("PrintFormData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Remove_Scan_Sign {
            get {
                return this.Remove_Scan_SignField;
            }
            set {
                if ((this.Remove_Scan_SignField.Equals(value) != true)) {
                    this.Remove_Scan_SignField = value;
                    this.RaisePropertyChanged("Remove_Scan_Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Serial_Number {
            get {
                return this.Serial_NumberField;
            }
            set {
                if ((this.Serial_NumberField.Equals(value) != true)) {
                    this.Serial_NumberField = value;
                    this.RaisePropertyChanged("Serial_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source_Directory {
            get {
                return this.Source_DirectoryField;
            }
            set {
                if ((object.ReferenceEquals(this.Source_DirectoryField, value) != true)) {
                    this.Source_DirectoryField = value;
                    this.RaisePropertyChanged("Source_Directory");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Source_File_CheckSum {
            get {
                return this.Source_File_CheckSumField;
            }
            set {
                if ((object.ReferenceEquals(this.Source_File_CheckSumField, value) != true)) {
                    this.Source_File_CheckSumField = value;
                    this.RaisePropertyChanged("Source_File_CheckSum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SurrKey {
            get {
                return this.SurrKeyField;
            }
            set {
                if ((this.SurrKeyField.Equals(value) != true)) {
                    this.SurrKeyField = value;
                    this.RaisePropertyChanged("SurrKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool TrackChanges {
            get {
                return this.TrackChangesField;
            }
            set {
                if ((this.TrackChangesField.Equals(value) != true)) {
                    this.TrackChangesField = value;
                    this.RaisePropertyChanged("TrackChanges");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string User_Id {
            get {
                return this.User_IdField;
            }
            set {
                if ((object.ReferenceEquals(this.User_IdField, value) != true)) {
                    this.User_IdField = value;
                    this.RaisePropertyChanged("User_Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="File_Operations", Namespace="http://schemas.datacontract.org/2004/07/eDocsDN_Get_Directory_Info")]
    [System.SerializableAttribute()]
    public partial class File_Operations : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eDocsDN_File_Server_Operations.FileServer.LockUnlockFile LockUnlockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eDocsDN_File_Server_Operations.FileServer.Scan_Signature ScanSignatureField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eDocsDN_File_Server_Operations.FileServer.Update_Users_Comments UpdateCommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eDocsDN_File_Server_Operations.FileServer.Update_Document_Custom_Variables Update_PropertiesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eDocsDN_File_Server_Operations.FileServer.LockUnlockFile LockUnlock {
            get {
                return this.LockUnlockField;
            }
            set {
                if ((object.ReferenceEquals(this.LockUnlockField, value) != true)) {
                    this.LockUnlockField = value;
                    this.RaisePropertyChanged("LockUnlock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eDocsDN_File_Server_Operations.FileServer.Scan_Signature ScanSignature {
            get {
                return this.ScanSignatureField;
            }
            set {
                if ((object.ReferenceEquals(this.ScanSignatureField, value) != true)) {
                    this.ScanSignatureField = value;
                    this.RaisePropertyChanged("ScanSignature");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eDocsDN_File_Server_Operations.FileServer.Update_Users_Comments UpdateComments {
            get {
                return this.UpdateCommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.UpdateCommentsField, value) != true)) {
                    this.UpdateCommentsField = value;
                    this.RaisePropertyChanged("UpdateComments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eDocsDN_File_Server_Operations.FileServer.Update_Document_Custom_Variables Update_Properties {
            get {
                return this.Update_PropertiesField;
            }
            set {
                if ((object.ReferenceEquals(this.Update_PropertiesField, value) != true)) {
                    this.Update_PropertiesField = value;
                    this.RaisePropertyChanged("Update_Properties");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LockUnlockFile", Namespace="http://schemas.datacontract.org/2004/07/eDocsDN_Get_Directory_Info")]
    [System.SerializableAttribute()]
    public partial class LockUnlockFile : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LockFileField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eDocsDN_File_Server_Operations.FileServer.LockType Lock_TypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LockFile {
            get {
                return this.LockFileField;
            }
            set {
                if ((this.LockFileField.Equals(value) != true)) {
                    this.LockFileField = value;
                    this.RaisePropertyChanged("LockFile");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eDocsDN_File_Server_Operations.FileServer.LockType Lock_Type {
            get {
                return this.Lock_TypeField;
            }
            set {
                if ((this.Lock_TypeField.Equals(value) != true)) {
                    this.Lock_TypeField = value;
                    this.RaisePropertyChanged("Lock_Type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Scan_Signature", Namespace="http://schemas.datacontract.org/2004/07/eDocsDN_Get_Directory_Info")]
    [System.SerializableAttribute()]
    public partial class Scan_Signature : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool Remove_Scan_SignField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> Users_Scan_SignField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Remove_Scan_Sign {
            get {
                return this.Remove_Scan_SignField;
            }
            set {
                if ((this.Remove_Scan_SignField.Equals(value) != true)) {
                    this.Remove_Scan_SignField = value;
                    this.RaisePropertyChanged("Remove_Scan_Sign");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> Users_Scan_Sign {
            get {
                return this.Users_Scan_SignField;
            }
            set {
                if ((object.ReferenceEquals(this.Users_Scan_SignField, value) != true)) {
                    this.Users_Scan_SignField = value;
                    this.RaisePropertyChanged("Users_Scan_Sign");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Update_Users_Comments", Namespace="http://schemas.datacontract.org/2004/07/eDocsDN_Get_Directory_Info")]
    [System.SerializableAttribute()]
    public partial class Update_Users_Comments : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime dtDateTimeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIDField, value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime dtDateTime {
            get {
                return this.dtDateTimeField;
            }
            set {
                if ((this.dtDateTimeField.Equals(value) != true)) {
                    this.dtDateTimeField = value;
                    this.RaisePropertyChanged("dtDateTime");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Update_Document_Custom_Variables", Namespace="http://schemas.datacontract.org/2004/07/eDocsDN_Get_Directory_Info")]
    [System.SerializableAttribute()]
    public partial class Update_Document_Custom_Variables : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private eDocsDN_File_Server_Operations.FileServer.Documents_Process eDocument_ProcessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public eDocsDN_File_Server_Operations.FileServer.Documents_Process eDocument_Process {
            get {
                return this.eDocument_ProcessField;
            }
            set {
                if ((this.eDocument_ProcessField.Equals(value) != true)) {
                    this.eDocument_ProcessField = value;
                    this.RaisePropertyChanged("eDocument_Process");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LockType", Namespace="http://schemas.datacontract.org/2004/07/eDocsDN_Get_Directory_Info")]
    public enum LockType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ReadOnly = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Comments = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TrackedChanges = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Forms = 4,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Documents_Process", Namespace="http://schemas.datacontract.org/2004/07/eDocsDN_Get_Directory_Info")]
    public enum Documents_Process : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Controller_Live = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Transfer_Document = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Controller_Publish = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Document_Recall = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TR4 = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Document_Issuance = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Preview = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PDC = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Update_User_Comments = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Attach_Custom_Variables = 9,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FileServer.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CopyFile", ReplyAction="http://tempuri.org/IService1/CopyFileResponse")]
        bool CopyFile(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CopyFile", ReplyAction="http://tempuri.org/IService1/CopyFileResponse")]
        System.Threading.Tasks.Task<bool> CopyFileAsync(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Check_File_Exist", ReplyAction="http://tempuri.org/IService1/Check_File_ExistResponse")]
        bool Check_File_Exist(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Check_File_Exist", ReplyAction="http://tempuri.org/IService1/Check_File_ExistResponse")]
        System.Threading.Tasks.Task<bool> Check_File_ExistAsync(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_File_Information", ReplyAction="http://tempuri.org/IService1/Get_File_InformationResponse")]
        eDocsDN_File_Server_Operations.FileServer.File_Data Get_File_Information(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Get_File_Information", ReplyAction="http://tempuri.org/IService1/Get_File_InformationResponse")]
        System.Threading.Tasks.Task<eDocsDN_File_Server_Operations.FileServer.File_Data> Get_File_InformationAsync(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Check_File_Is_Locked", ReplyAction="http://tempuri.org/IService1/Check_File_Is_LockedResponse")]
        bool Check_File_Is_Locked(string szFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Check_File_Is_Locked", ReplyAction="http://tempuri.org/IService1/Check_File_Is_LockedResponse")]
        System.Threading.Tasks.Task<bool> Check_File_Is_LockedAsync(string szFileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_File", ReplyAction="http://tempuri.org/IService1/Delete_FileResponse")]
        bool Delete_File(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/Delete_File", ReplyAction="http://tempuri.org/IService1/Delete_FileResponse")]
        System.Threading.Tasks.Task<bool> Delete_FileAsync(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : eDocsDN_File_Server_Operations.FileServer.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<eDocsDN_File_Server_Operations.FileServer.IService1>, eDocsDN_File_Server_Operations.FileServer.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool CopyFile(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData) {
            return base.Channel.CopyFile(oFileData);
        }
        
        public System.Threading.Tasks.Task<bool> CopyFileAsync(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData) {
            return base.Channel.CopyFileAsync(oFileData);
        }
        
        public bool Check_File_Exist(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData) {
            return base.Channel.Check_File_Exist(oFileData);
        }
        
        public System.Threading.Tasks.Task<bool> Check_File_ExistAsync(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData) {
            return base.Channel.Check_File_ExistAsync(oFileData);
        }
        
        public eDocsDN_File_Server_Operations.FileServer.File_Data Get_File_Information(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData) {
            return base.Channel.Get_File_Information(oFileData);
        }
        
        public System.Threading.Tasks.Task<eDocsDN_File_Server_Operations.FileServer.File_Data> Get_File_InformationAsync(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData) {
            return base.Channel.Get_File_InformationAsync(oFileData);
        }
        
        public bool Check_File_Is_Locked(string szFileName) {
            return base.Channel.Check_File_Is_Locked(szFileName);
        }
        
        public System.Threading.Tasks.Task<bool> Check_File_Is_LockedAsync(string szFileName) {
            return base.Channel.Check_File_Is_LockedAsync(szFileName);
        }
        
        public bool Delete_File(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData) {
            return base.Channel.Delete_File(oFileData);
        }
        
        public System.Threading.Tasks.Task<bool> Delete_FileAsync(eDocsDN_File_Server_Operations.FileServer.File_Data oFileData) {
            return base.Channel.Delete_FileAsync(oFileData);
        }
    }
}
